---
- name: Listen for index 27
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 30
  rules:
    - name: Trigger when index is 27
      condition: event.i == 27
      action:
        debug:
          msg: "I am learning to write a rulebook as a part of training"
